### ISSUE TITLE
How should this be run?

### ISSUE THREAD

**Issue by cbrew** [explosion/spacy-services#1]
I tried a few things, and have had no success so far. It looks to me as if 

``gunicorn <something>``

might be close.

**Comment by honnibal** [comment]
Sorry I missed this in the docs! Will update.

If you're just hacking locally, `python displacy/app.py` or `python/sense2vec/app.py` should do the trick.

**Comment by cbrew** [comment]
One reason why that doesn't work is that displacy/app.py refers to displacy.server, and should probably refer to displacy_service.server, to match the name of the directory. I can fix that, but it doesn't seem to be enough.

**Comment by honnibal** [comment]
Is this resolved now? I just made a quick hot-fix in the web UI that I think addresses the schema issues.

**Comment by cbrew** [comment]
still seeing 

curl -s localhost:8000/en/schema
{
    "title": "Schema construction failed",
    "description": "'spacy.tagger.Tagger' object has no attribute 'moves'"
}

for 

spacy.__version__ == '1.6.0' 
 Python 3.5.2 |Anaconda custom (x86_64)|
